import Head from "next/head";
import styles from "@/styles/Home.module.css";
import axios from "axios";

export default function Home({ movies }) {
  return (
    <>
      <Head>
        <title>Ma première App Next</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <h1>Coucou</h1>
      </main>
    </>
  );
}

export async function getServersideProps() {
  console.log("coucou !");
  try {
    const { fetchMovies } = await axios.get(
      "https://lereacteur-bootcamp-api.herokuapp.com/api/allocine/movies/top_rated",
      {
        headers: {
          Authorization: `Bearer ${process.env.MOVIE_API_KEY}`,
        },
      }
    );
    console.log(fetchMovies);
  } catch (error) {
    console.log(error);
  }

  return {
    props: {
      movies: fetchMovies,
    },
  };
}
